# .travis.yml: Travis CI config
#
# Copyright (C) 2020 Stephen G. Tuggy <sgt@stephengtuggy.com>
#
# This file is part of Vega Strike.
#
# Vega Strike is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Vega Strike is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Vega Strike.  If not, see <https://www.gnu.org/licenses/>.

language: cpp
os: linux

services:
  - docker

dist: focal

jobs:
    include:
        - os: linux
          name: "Ubuntu 20.04 LTS focal"
          env:
            - FROM='ubuntu:focal'
        - os: linux
          name: "Ubuntu 18.04 LTS bionic"
          env:
            - FROM='ubuntu:bionic'
        - os: linux
          name: "Ubuntu 16.04 LTS xenial"
          env:
            - FROM='ubuntu:xenial'
        - os: linux
          name: "Debian 10 buster"
          env:
            - FROM='debian:buster'
        - os: linux
          name: "Debian 9 stretch"
          env:
            - FROM='debian:stretch'
        - os: linux
          name: "openSUSE Leap 15.2"
          env:
            - FROM='opensuse/leap'
        - os: linux
          name: "Fedora 32"
          env:
            - FROM='fedora:32'
        - os: linux
          name: "Fedora 31"
          env:
            - FROM='fedora:31'
        - os: linux
          name: "CentOS 8"
          env:
            - FROM='centos:8'
script:
  - ./script/cibuild
