name: Anchore-Container-Scan

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM:     'ubuntu:kinetic'
          - FROM:     'ubuntu:jammy'
          - FROM:     'ubuntu:focal'
          - FROM:     'ubuntu:bionic'
          - FROM:     'linuxmintd/mint21.1-amd64'
          - FROM:     'linuxmintd/mint21-amd64'
          - FROM:     'linuxmintd/mint20-amd64'
          - FROM:     'debian:bookworm'
          - FROM:     'debian:bullseye'
          - FROM:     'debian:buster'
          - FROM:     'debian:stretch'
          - FROM:     'opensuse/leap'
          - FROM:     'opensuse/leap:15.4'
          - FROM:     'opensuse/leap:15.3'
          - FROM:     'opensuse/leap:15.2'
          - FROM:     'fedora:37'
          - FROM:     'fedora:36'
          - FROM:     'fedora:35'
          - FROM:     'fedora:34'
          - FROM:     'rockylinux/rockylinux'
          - FROM:     'rockylinux:9.1'
          - FROM:     'rockylinux:9.0'
          - FROM:     'rockylinux:8.7'
          - FROM:     'rockylinux:8.6'
          - FROM:     'rockylinux:8.5'
          - FROM:     'manjarolinux/base'
          - FROM:     'funtoo/stage3-generic_64'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
        with:
          fetch-depth: 2
          submodules: false

      # - name: Run CI
      #   env:
      #     FROM:       ${{ matrix.FROM }}
      #     MY_OS_NAME: linux
      #     IS_RELEASE: 0
      #   run: script/cibuild

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 #v2.2.1
        env:
          FROM:       ${{ matrix.FROM }}
          MY_OS_NAME: linux
          IS_RELEASE: 1

      - name: build local container
        uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3 #v3.3.0
        env:
          FROM:       ${{ matrix.FROM }}
          MY_OS_NAME: linux
          IS_RELEASE: 1
        with:
          build-args: from=${{ matrix.FROM }}
          tags: localbuild/${{ matrix.FROM }}
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@9a22e4caae42db0d4c687ab5431e1c3699d0def1 #v3.3.2
        with:
          image: "localbuild/${{ matrix.FROM }}"
          fail-build: false
          severity-cutoff: critical
