name: 'GH Actions - Release'

on:
  release:
    types:
      - created
      - edited


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: production

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM:     'ubuntu:hirsute'
          - FROM:     'ubuntu:groovy'
          - FROM:     'ubuntu:focal'
          - FROM:     'ubuntu:bionic'
          - FROM:     'ubuntu:xenial'
          - FROM:     'linuxmintd/mint20-amd64'
          - FROM:     'debian:bullseye'
          - FROM:     'debian:buster'
          - FROM:     'debian:stretch'
          - FROM:     'opensuse/leap'
          - FROM:     'fedora:34'
          - FROM:     'fedora:33'
          - FROM:     'fedora:32'
          - FROM:     'rockylinux/rockylinux'
          # - FROM:     'centos:8'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
        submodules: false

    # where in a pull request we want to move to the head of the PR and not be at the
    # merge commit; here we want to be at the HEAD of the ref

    - name: Extract tag name etc
      shell: bash
      run: |
        echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV

    - name: Test tag name etc
      run: |
        echo "${TAG_NAME}"

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_KEY }}

    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        MY_OS_NAME: linux
        IS_RELEASE: 1
      run: script/cibuild
