name: 'GH Actions - PR'

on: [ pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        FROM:
          - 'ubuntu:mantic'
          - 'ubuntu:jammy'
          - 'ubuntu:focal'
          - 'ubuntu:bionic'
          - 'linuxmintd/mint21.1-amd64'
          - 'linuxmintd/mint21-amd64'
          - 'linuxmintd/mint20-amd64'
          - 'debian:bookworm'
          - 'debian:bullseye'
          - 'debian:buster'
          - 'opensuse/leap:15.5'
          - 'opensuse/leap:15.4'
          - 'opensuse/leap:15.3'
          - 'opensuse/leap:15.2'
          - 'fedora:40'
          - 'fedora:39'
          - 'fedora:38'
          - 'fedora:37'
          - 'fedora:36'
          - 'fedora:35'
          - 'fedora:34'
          - 'rockylinux:9.3'
          - 'rockylinux:9.2'
          - 'rockylinux:9.1'
          - 'rockylinux:9.0'
          - 'rockylinux:8.9'
          - 'rockylinux:8.8'
          - 'rockylinux:8.7'
          - 'rockylinux:8.6'
          - 'rockylinux:8.5'
          - 'manjarolinux/base'
          #- 'funtoo/stage3-generic_64'

    steps:
    - name: Checkout repository
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f #v4.1.3
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can check out the head.
        fetch-depth: 2
        submodules: false

    # Ensure PRs are built against the PR Head
    # As opposed to the merge commit
    - name: Move to PR HEAD
      run: git checkout HEAD^2
    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        MY_OS_NAME: linux
        IS_RELEASE: 0
      run: script/cibuild
