name: 'GH Actions - Release'

on:
  release:
    types:
      - created
      - edited


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: production

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM:     'ubuntu:jammy'
          - FROM:     'ubuntu:focal'
          - FROM:     'ubuntu:bionic'
          - FROM:     'linuxmintd/mint21-amd64'
          - FROM:     'linuxmintd/mint20-amd64'
          - FROM:     'debian:bookworm'
          - FROM:     'debian:bullseye'
          - FROM:     'debian:buster'
          - FROM:     'debian:stretch'
          - FROM:     'opensuse/leap'
          - FROM:     'opensuse/leap:15.4'
          - FROM:     'opensuse/leap:15.3'
          - FROM:     'opensuse/leap:15.2'
          - FROM:     'fedora:37'
          - FROM:     'fedora:36'
          - FROM:     'fedora:35'
          - FROM:     'fedora:34'
          - FROM:     'rockylinux/rockylinux'
          - FROM:     'rockylinux:9.0'
          - FROM:     'rockylinux:8.6'
          - FROM:     'rockylinux:8.5'
          - FROM:     'manjarolinux/base'

    steps:
    - name: Checkout repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
      with:
        fetch-depth: 2
        submodules: false

    - name: Extract tag name etc
      shell: bash
      run: |
        echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV

    - name: Test tag name etc
      run: |
        echo "${TAG_NAME}"

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_KEY }}

    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        MY_OS_NAME: linux
        IS_RELEASE: 1
      run: script/cibuild
