name: 'GH Actions - PR'

on: [ pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - FROM:     'ubuntu:kinetic'
          - FROM:     'ubuntu:jammy'
          - FROM:     'ubuntu:focal'
          - FROM:     'ubuntu:bionic'
          - FROM:     'linuxmintd/mint21.1-amd64'
          - FROM:     'linuxmintd/mint21-amd64'
          - FROM:     'linuxmintd/mint20-amd64'
          - FROM:     'debian:bookworm'
          - FROM:     'debian:bullseye'
          - FROM:     'debian:buster'
          - FROM:     'opensuse/leap'
          - FROM:     'opensuse/leap:15.4'
          - FROM:     'opensuse/leap:15.3'
          - FROM:     'opensuse/leap:15.2'
          - FROM:     'fedora:37'
          - FROM:     'fedora:36'
          - FROM:     'fedora:35'
          - FROM:     'fedora:34'
          - FROM:     'rockylinux/rockylinux'
          - FROM:     'rockylinux:9.1'
          - FROM:     'rockylinux:9.0'
          - FROM:     'rockylinux:8.7'
          - FROM:     'rockylinux:8.6'
          - FROM:     'rockylinux:8.5'
          - FROM:     'manjarolinux/base'
          - FROM:     'funtoo/stage3-generic_64'

    steps:
    - name: Checkout repository
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 #v3.5.0
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can check out the head.
        fetch-depth: 2
        submodules: false

    # Ensure PRs are built against the PR Head
    # As opposed to the merge commit
    - name: Move to PR HEAD
      run: git checkout HEAD^2
    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        MY_OS_NAME: linux
        IS_RELEASE: 0
      run: script/cibuild
